### ISSUE TITLE
Secrets Management: The implementing folder should be called `SecretsManagementExtension`

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/Modules#22]
Currently, the module expects extensions to be in a folder called `ImplementingModule` and also the module to have that name.  We should call it something more specific like `SecretsManagementExtension` as we may use this model for other types of extensions in the future.

**Comment by JustinGrote** [comment]
Either this or use a .psd1 manifest variable in PrivateData or whatnot so the module can designate where the code is. 

It would be ideal if a Powershell Script module could just expose a secrets management interface without having to ship an entirely separate module, similar to how DSC works today.

**Comment by PaulHigin** [comment]
This has been addressed with PR (#39).
