### ISSUE TITLE
[SecretsManagement] CredManager Naming Convention should be ps:SecretName

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/Modules#24]
# Summary of the new feature/enhancement

Secrets are stored in Windows Credential Manager as `__PS_<secretName>`. The more common convention seen by popular tools such as git, azure devops, Microsoft Account, WindowsLive, etc. is `ps:<secretname>`. The module should adopt this de-facto convention for consistency for this provider.

Other possibilities:
`powershell:<secretname>`
`pwsh:<secretname>`
`psSecretManagement:<secretname>`

### Prior Art Examples

![image](https://user-images.githubusercontent.com/15258962/73987256-952a0300-48f4-11ea-93d7-5552ca666006.png)

![image](https://user-images.githubusercontent.com/15258962/73987270-a2df8880-48f4-11ea-8a58-1a82dfd8e46f.png)

![image](https://user-images.githubusercontent.com/15258962/73987276-a83cd300-48f4-11ea-8e36-31b90881dd69.png)
![image](https://user-images.githubusercontent.com/15258962/73987284-ad9a1d80-48f4-11ea-848f-a1e26e5e3307.png)
![image](https://user-images.githubusercontent.com/15258962/73987286-b25ed180-48f4-11ea-9629-371b4c4e0b57.png)

**Comment by SydneyhSmith** [comment]
`ps:<secretname>` makes sense to use, thanks @JustinGrote

**Comment by PaulHigin** [comment]
Done.
