### ISSUE TITLE
Cannot install module from powershell 5.1

### ISSUE THREAD

**Issue by Kettoch** [PowerShell/Modules#34]
The PSH Gallery says that the minimum version is 5.1.

However, the module will not install under 5.1 but with 7 only.

**Comment by PaulHigin** [comment]
I am not able to repro this.  More information is needed.  I did need to update my `PackageManagement` and `PowerShellGet` modules to the latest versions, that support the `-AllowPrerelease` switch.  But then I was able to install the module under Windows PowerShell:

```powershell
Install-Module microsoft.powershell.secretsmanagement -Force -AllowPrerelease
```

**Comment by SydneyhSmith** [comment]
Closing this as we are not able to repro, if you can provide more information we will re-open--thanks!
