### ISSUE TITLE
[SecretsManagment][Feature] Add-Secret should be named Set-Secret

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/Modules#37]
In the interface for the Secret Vaults, we have `Set-Secret` as the verb, and the vault is expected to automatically overwrite any secret that already existed with that name. 

But in the public module commands, you've incorrectly used the verb `Add` with a very unintuitive `NoClobber` switch. This is confusing for users, but even more confusing for anyone who's studied the RFC or the vault design and seen `Set-Secret` all over the place.

# We need consistent use of verbs

It's not just PowerShell, but in _programming in general_, the **Add** verb is used for non-destructive operations where you are appending to a collection without overwriting anything that's already in the collection.

In PowerShell the built-in `Add` commands are implemented this way, and in the rare occasion where they have the _ability_ to overwrite, it must be explicitly invoked with a `-Force` switch.

- `Add-Content` does not _replace_ the content, it adds to it.
- `Add-History` does not _replace_ the history, it adds to it.
- `Add-Type` cannot replace a type definition ...
- `Add-Member` does not _overwrite_ existing members with the same name _unless_ you specify `-Force`
...

In fact, that's usually also true for the `New` verb, for example:
- `New-Alias` does not _overwrite_ existing aliases _unless_ you specify `-Force`

When we want to overwrite, or to change the value of something, we use the verb `Set`:
- `Set-Content` replaces the contents without warning
- `Set-Alias` does not care if the alias already exists

As an additional point: the `-NoClobber` parameter, although common, has never been used on an `Add` command before now. It's usually used only with verbs that _implicitly_ create things, such as `Export` and `Write`

And further, the `Add-Secret` command is implemented by [**literally** invoking `set-secret`](https://github.com/PowerShell/Modules/blob/master/Modules/Microsoft.PowerShell.SecretsManagement/src/code/SecretsManagement.cs#L1060)!, and the comment on the line above it is _incorrect_ because it's not **necessarily** a new secret (unless the user specified `-NoClobber` to make the command behave the way an `Add` command _should_ behave).

# Proposed technical implementation details

Please rename `AddSecretCommand` command to `SetSecretCommand` and change the verb to `Set`. 

Alternatively: change the `NoClobber` parameter to `Force` and invert the logic so that it defaults to _not_ clobbering, as users will expect.

**Comment by JustinGrote** [comment]
Related to #30, we want to uphold the "Powershell Promise" that people won't have to relean Powershell once they learn it, so the conventions in this command should behave as similar as possible to common commands users are familiar to like the *-Item commands.


I slightly disagree with @Jaykul to the verb choice however. If you choose Set-Secret, it should overwrite by default. If you choose New-Secret, it should error if a duplicate exists unless `-force` is specified. Of course both can be specified and just have Set-Secret call New-Secret `-Force`

**Comment by Jaykul** [comment]
@JustinGrote I agree, and that's what I meant. The current command (which overwrites by default) is implemented as `Set` and would be ok if it was named that. 

Although I have to say, if I were creating this whole thing, I would have implemented is as a _PSProvider_...

**Comment by JustinGrote** [comment]
@Jaykul we can still do that with SHIPS :). One folder per provider, then the secrets under there.

**Comment by jeremymcgee73** [comment]
I want to add that the example script does not actually overwrite.[ It throws an error](https://github.com/PowerShell/Modules/blob/7570c0352c5c53947a134d4baa9f30bc73a53675/Samples/VaultExtension/Modules/ScriptLocalVault/SecretsManagementExtension/SecretsManagementExtension.psm1#L47) if the secret exists. That is what my module currently does as well.

**Comment by Jaykul** [comment]
The "example"?  The actual default provider does not do that. Besides, if you throw an error when the secret exists, how can you update a secret @jeremymcgee73?

**Comment by SydneyhSmith** [comment]
Thanks for all the feedback, closing as a result of PR #51
