### ISSUE TITLE
[SecretsManagement] Get-Secret returns the first item in a ByteArray

### ISSUE THREAD

**Issue by jeremymcgee73** [PowerShell/Modules#40]
When returning a bytearray in Get-Secret, only the first item of the array is returned. This should return the whole array to properly support ByteArrays. I worked on this for a few hours thinking it was my implementation. Then, I realized It was a bug. Thanks!

# Steps to reproduce

```powershell
function Get-Secret
{
    param (
        [string] $Name,
        [hashtable] $AdditionalParameters
    )

    if ([WildcardPattern]::ContainsWildcardCharacters($Name))
    {
        throw "The Name parameter cannot contain wild card characters."
    }

    $enc = [system.Text.Encoding]::UTF8
    $string1 = "Testing byte array"
    $Array = $enc.GetBytes($string1)

    return $Array
}
```

# Expected behavior

```powershell
(Get-Secret -Name "Binary" -Vault "Test").GetType().Name
Byte[]
```

# Actual behavior

```powershell
(Get-Secret -Name "Binary" -Vault "Test").GetType().Name
Byte
```

**Comment by PaulHigin** [comment]
This is a PowerShell peculiarity, where the pipeline automatically uwraps object arrays.  I forgot to fix this in my test script extension, but have it in my tests.  You need to do the following:

```powershell
$secret = $enc.GetBytes($string1)
...

if ($secret -is [byte[]])
{
    return @(,$secret)  # Return as array instead of individual array objects.
}
```

I'll update my test extension to do this.
