### ISSUE TITLE
[SecretManagement][Minor]Update Repository readme to remove plurality

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/Modules#56]
https://github.com/PowerShell/Modules/blob/master/README.md#microsoftpowershellsecretsmanagement

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote I opened PR https://github.com/PowerShell/Modules/pull/58 to update this.

**Comment by PaulHigin** [comment]
Fixed.  Thanks.
