### ISSUE TITLE
[SecretManagement] Build - PSPackageProject Check should be called prior to usage of its cmdlets

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/Modules#57]
https://github.com/PowerShell/Modules/blob/ef9b4bb2627f0590e848ec75bd79a708e153213a/Modules/Microsoft.PowerShell.SecretManagement/build.ps1#L49-L51

Should come before

https://github.com/PowerShell/Modules/blob/ef9b4bb2627f0590e848ec75bd79a708e153213a/Modules/Microsoft.PowerShell.SecretManagement/build.ps1#L33

Or better, placed in the requirements at the top (Line 1: `#requires -module PSPackageProject`)

**Comment by PaulHigin** [comment]
Good find.  Thanks.
