### ISSUE TITLE
Typo Register-Secret(s)Vault on homepage of Microsoft.PowerShell.SecretsManagement

### ISSUE THREAD

**Issue by dingmeng-xue** [PowerShell/Modules#63]
The example about Register-SecretsVault missed 's'

https://github.com/PowerShell/Modules/tree/master/Modules/Microsoft.PowerShell.SecretsManagement

**Comment by nlsdg** [comment]
The 's' isn't missing. They've changed the names of the module and commandlets.
See pull request #53 and the blog post on https://devblogs.microsoft.com/powershell/secret-management-preview-2-release/

**Comment by SydneyhSmith** [comment]
Thanks for opening the issue @dingmeng-xue , @nlsdg is correct, this change reflects the change we made to the name of the module...so I will go ahead and mark this issue as answered...thanks
