### ISSUE TITLE
Rename Test-Vault to Test-SecretVault

### ISSUE THREAD

**Issue by jhochwald** [PowerShell/Modules#65]
# Summary of the new feature/enhancement

The Test-SecretVault would be the same naming convention that the rest of the commands have.
In general the Test-Vault is fine, it’s really just a naming convention issue in my opinion.

# Proposed technical implementation details (optional)

Should be none

**Comment by SydneyhSmith** [comment]
Thanks @jhochwald you are correct, it should be Test-SecretVault, and in fact the code already represents that an issue I will clean up in the documentation. Thanks! 
https://github.com/PowerShell/Modules/blob/ef9b4bb2627f0590e848ec75bd79a708e153213a/Modules/Microsoft.PowerShell.SecretManagement/TestExtensionModules/TestLocalScript/SecretManagementExtension/SecretManagementExtension.psd1#L4
