### ISSUE TITLE
'Modules/Modules/Microsoft.PowerShell.SecretsManagement/' still available in repository

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/Modules#66]
Even after rename of module was published the now obsolete module 'SecretsManagement' is visible in repository. From my view this obsolete module 'SecretsManagement' should be be deleted to avoid confusion for users. Maybe related to #63

**Comment by SydneyhSmith** [comment]
@mi-hol thanks for opening this issue, we will plan to remove this folder. Thanks!

**Comment by PaulHigin** [comment]
This old version has been removed.
